### ISSUE TITLE
cannot show process on mac

### ISSUE THREAD

**Issue by kenchou** [gazorby/fifc#13]
**Describe the bug**
```
❯ kill ps: illegal option -- -
usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]]
          [-g grp[,grp...]] [-u [uid,uid...]]
```

**System (please complete the following information):**

- fish version 3.5.1
- Mac OS 12.5

**Comment by gazorby** [comment]
Hi @kenchou !

Are you on the latest fifc?
Can you run `fisher update gazorby/fifc` and test if it still happens?

**Comment by kenchou** [comment]
It's latest. I'm first install.
problem is here: https://github.com/gazorby/fifc/blob/main/conf.d/fifc.fish#L26
The options of ps on mac os (BSD) are difference

Linux | Mac OS | memo
----- | -------- | ------
--format pid,command | `-o pid,command` | option `-o` both available on linux/mac
--no-headers |  | no similar options

**Comment by gazorby** [comment]
Oh I see, thanks pointed that out.

So `ps -ax -o pid=,command=` should give the desired output

**Comment by kenchou** [comment]
Yes, I'm tried it. seems fine both on mac and linux 

```
fifc \
    -n 'test "$fifc_group" = processes' \
    -s 'ps -ax -o pid=,command='
```
