### ISSUE TITLE
The plugin throws an error when pressing `tab` after typing some commands

### ISSUE THREAD

**Issue by HamzaBow** [gazorby/fifc#2]
The plugin displays errors when executing some commands
e.g. using it with the `ls` or `exa` commands causes an error, whereas pressing `tab` after typing `git` or `bat` doesn't cause any error and it works OK in the latter cases
**To Reproduce**
`fisher install gazorby/fifc `
`set -Ux fifc_editor vim`

In the screenshot bellow I typed `exa --color=always` and then pressed `tab` and this happened:

![image](https://user-images.githubusercontent.com/71119861/177166209-69cbc184-505d-48b8-9e66-f31712d702b2.png)

I think it has to do with `fd` command, I have installed fd this way:
`sudo apt install fd-find`
and then I aliased it
`alias fd fdfind`

**System:**

- fish: version 3.5.0
- Distribution: Ubuntu 20.04.4 LTS (Focal Fossa)

**Comment by gazorby** [comment]
Ok, it seems that `--strip-cwd-prefix` has been in a recent release of fd ([8.3.0](https://github.com/sharkdp/fd/releases/tag/v8.3.0)) that you might no have installed.

**Comment by gazorby** [comment]
Fixed in master, `--strip-cwd-prefix` is removed now. You can still add it using `fifc_fd_opts`

**Comment by kidonng** [comment]
No need to remove it, just [do a simple version check](https://github.com/PatrickF1/fzf.fish/pull/211) is fine.

**Comment by gazorby** [comment]
Right, that was more a hotfix than a solution
