### ISSUE TITLE
macOS: TAB completion  causes "sed: invalid command code f" error

### ISSUE THREAD

**Issue by amok** [gazorby/fifc#22]
**Describe the bug**

When I press "TAB" for autocompletion error is shown. Also, "description" pane shows the same error when "in fzf".

```sh
~ ❯ fisher rsed: 1: "/var/folders/rz/dz8mzhp ...": invalid command code f 
```

**To Reproduce**

It's how the plugin works for me right after installation

**Expected behavior**
Autocompletion should not throw an error

**Screenshots**

![image](https://user-images.githubusercontent.com/1369559/211868687-81f6104b-ed98-41d4-a8ba-ca7464d4fa45.png)

![image](https://user-images.githubusercontent.com/1369559/211870006-55e2e2ef-10e6-4dd8-8a01-5295b02cb20a.png)

**System (please complete the following information):**

- fish, version 3.6.0
- Distribution: Darwin macOS 22.2.0(SORRY_NO_PSEUDONAME 22C65 arm64)

**Additional context**

The error I believe happens on https://github.com/gazorby/fifc/blob/adff5966739667d4c13d6388372e40f821571208/functions/_fifc_action.fish#L10

and is triggered by https://github.com/gazorby/fifc/blob/adff5966739667d4c13d6388372e40f821571208/functions/_fifc.fish#L25

since the second argument is not set `printf -- ...` evaluates to an empty string which later causes `sed` to fail

 I guess the fix would be to just remove `--` in `printf` call, [since](https://fishshell.com/docs/3.4/cmds/printf.html#description)
 
![image](https://user-images.githubusercontent.com/1369559/211916715-d3bb252a-77ee-4387-a1c5-ada8dc197529.png)

(at least this fixes the bug for me)

**Comment by gazorby** [comment]
Thanks for this! Also fixed on main ;)
