### ISSUE TITLE
macOS: Preview of command options shows error "head: illegal line count -- -1"

### ISSUE THREAD

**Issue by amok** [gazorby/fifc#23]
**Describe the bug**
Preview of command options shows error `head: illegal line count -- -1` on macOS

**To Reproduce**
Type f.e. `cat -` in and then press `TAB` (to trigger `fifc`)

**Expected behavior**
No error in preview pane

**Screenshots**
![image](https://user-images.githubusercontent.com/1369559/211927808-582e69db-0a1b-4e93-95a0-ce5c2b6f0b61.png)

**System (please complete the following information):**

- fish, version 3.6.0
- Distribution: Darwin macOS 22.2.0(SORRY_NO_PSEUDONAME 22C65 arm64)

**Additional context**

Mostly likely the error happens on https://github.com/gazorby/fifc/blob/adff5966739667d4c13d6388372e40f821571208/functions/_fifc_preview_opt.fish#L17

and it's probably due to the fact macOS' `head` does not support negative `-n` (lines count) value

**Comment by gazorby** [comment]
Thanks for the hint @amok! Should be fixed on main.
