### ISSUE TITLE
Problem passing "--icons --tree" to `fifc_exa_opts`

### ISSUE THREAD

**Issue by macintacos** [gazorby/fifc#32]
**Describe the bug**

I'm setting the `fifc_exa_opts` option like so:

```
set -U fifc_exa_opts "--icons --tree"
```

And when I hit "tab" after typing `cd `, I see an error in the preview that says:

```
exa: Unknown argument --icons --tree
```

This command works fine if executed directly, and I'm running the latest version of `exa` available.

**To Reproduce**

Set the option like I did above

**Expected behavior**

The preview would look like the output of `exa --icons --tree`.

**System (please complete the following information):**

- fish version - 3.6.1
- Distribution `cat /etc/os-release` - macOS 13.4.1

**Comment by gazorby** [comment]
Hi @macintacos!

This should be solved by setting options as list instead of string:

`set -U fifc_exa_opts --icons --tree`

Will mention it in the readme, thanks for the report!
